<?php
/*
 * GorKa Team
 * Copyright (c) 2023  Vlad Horpynych <19dynamo27@gmail.com>, Pavel Karpushevskiy <pkarpushevskiy@gmail.com>
 */

declare(strict_types = 1);

use DragonCode\LaravelActions\Action;

return new class () extends Action {
    /**
     * Run the actions.
     *
     * @return void
     */
    public function __invoke() : void
    {
        $createdAt = now();

        $commonOptions = [
            'created_at' => $createdAt,
            'updated_at' => $createdAt,
        ];

        \App\Models\Milestone::insert([
            array_merge($commonOptions, [
                'subdomain_id' => 1,
                'abbreviation' => 'GM.12',
                'title'        => 'Rückwärtsschritte machen',
                'text'         => 'Kind steht frei im Raum und bewegt sich mit mind. 3 Schritten hintereinander rückwärts, ohne sich irgendwo festzuhalten oder abzustützen.',
                'order'        => 1,
                'emphasis'     => 1,
                'emphasis_daz' => 1,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 1,
                'abbreviation' => 'GM.13',
                'title'        => 'Treppensteigen',
                'text'         => 'Kind geht in aufrechter Position und ohne fremde Hilfe (aber möglicherweise mit Abstützen an der Wand oder am Geländer) mind. 3 Treppenstufen aufwärts und 3 Treppenstufen abwärts. (Eine Richtung genügt nicht.)',
                'order'        => 2,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 1,
                'abbreviation' => 'GM.15',
                'title'        => 'Frei auf einem Bein stehen',
                'text'         => 'Kind hebt im freien Stand (ohne sich irgendwo festzuhalten) ein Bein vom Boden und hält in dieser Position mind. 3 Sekunden die Balance, ohne den zweiten Fuß wieder abstellen zu müssen.',
                'order'        => 3,
                'emphasis'     => 3,
                'emphasis_daz' => 3,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 1,
                'abbreviation' => 'GM.16',
                'title'        => 'Ohne Festhalten auf der Stelle hüpfen',
                'text'         => 'Kind hüpft mit beiden Beinen gleichzeitig hoch, so dass die Füße nicht mehr den Boden berühren, und landet wieder sicher im Stand.',
                'order'        => 4,
                'emphasis'     => 1,
                'emphasis_daz' => 1,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 2,
                'abbreviation' => 'GM.20',
                'title'        => 'Alleine von einer Stufe / einem Absatz springen und sicher landen',
                'text'         => 'Kind springt mit beiden Beinen gleichzeitig hoch, so dass die Füße nicht mehr den Boden berühren, überwindet im Sprung einen (kleinen) Absatz oder eine Stufe und landet wieder sicher im Stand.',
                'order'        => 5,
                'emphasis'     => 1,
                'emphasis_daz' => 1,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 3,
                'abbreviation' => 'GM.21',
                'title'        => 'Werfen eines Gegenstandes',
                'text'         => 'Kind hält ein Objekt über der Schulter (Nicht vor der Brust! Nicht neben dem Körper), streckt den Arm ganz nach vorne aus, um das Objekt gezielt und mit Schwung in eine bestimmte Richtung zu werfen. Das Objekt landet mind. einen halben Meter entfernt.',
                'order'        => 6,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 3,
                'abbreviation' => 'GM.22',
                'title'        => 'Ball mit den Armen fangen',
                'text'         => 'Kind fängt einen Ball mittlerer Größe, der ihm aus kurzer Entfernung (mind. 1 m) zugeworfen wird, mit beiden Armen auf, ohne dass er auf den Boden fällt.',
                'order'        => 7,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 4,
                'abbreviation' => 'GM.29',
                'title'        => 'Ohne fremde Hilfe auf einer Schaukel Schwung holen',
                'text'         => 'Kind holt auf der Schaukel sitzend selbstständig Schwung und schaukelt sich nach oben.',
                'order'        => 17,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 5,
                'abbreviation' => 'GM.37',
                'title'        => 'Von der Höhe einer 2. Treppenstufe springen',
                'text'         => 'Kind springt von der Höhe einer 2. Treppenstufe oder einer anderen Ebene ähnlicher Höhe und landet sicher, ohne das Gleichgewicht zu verlieren (kein Ausfallschritt, kein Abfangen mit der Hand).',
                'order'        => 18,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 5,
                'abbreviation' => 'GM.39',
                'title'        => 'Vorwärtssprung mit beiden Beinen',
                'text'         => 'Kind springt mit beiden Beinen gleichzeitig vorwärts und landet auch wieder auf beiden Beinen, ohne das Gleichgewicht zu verlieren (kein Ausfallschritt, kein Abfangen mit der Hand).',
                'order'        => 19,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 6,
                'abbreviation' => 'GM.40',
                'title'        => 'Sprung mit Gegenbewegung von Armen und Beinen',
                'text'         => 'Kind zeigt mind. zweimal eine Sprungfigur, bei der sich Arme und Beine jeweils in entgegengesetzte Richtung bewegen (z.B. Hampelmann-Sprung).',
                'order'        => 20,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 7,
                'abbreviation' => 'GM.44',
                'title'        => 'Plötzliches Losrennen',
                'text'         => 'Kind rennt nach Start-Signal sofort los und beschleunigt schnell.',
                'order'        => 21,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 7,
                'abbreviation' => 'GM.45',
                'title'        => 'Plötzlicher Bewegungsstop',
                'text'         => 'Kind stoppt sich nach Stopp-Signal sofort aus dem Laufen ab und kommt zum Stehen.',
                'order'        => 22,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 8,
                'abbreviation' => 'FM.10',
                'title'        => 'Mindestens drei Gegenstände stapeln',
                'text'         => 'Kind legt 3 Bauklötze oder andere Gegenstände gezielt aufeinander, so dass ein Turm entsteht, ohne dass etwas herunterfällt.',
                'order'        => 8,
                'emphasis'     => 4,
                'emphasis_daz' => 4,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 9,
                'abbreviation' => 'FM.11',
                'title'        => 'Alleine aus einem offenen Trinkgefäß trinken',
                'text'         => 'Kind hält ein mind. zur Hälfte gefülltes Trinkgefäß ohne Deckel, führt es zum Mund und trinkt daraus, ohne dass etwas daneben geht. Es zeigt dieses Verhalten mind. 3x.',
                'order'        => 9,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 9,
                'abbreviation' => 'FM.12',
                'title'        => 'Mit dem Löffel essen',
                'text'         => 'Kind hält einen mit halbfester Nahrung (z.B. Reis, Pudding, Kartoffelbrei...) beladenen Löffel gerade, führt ihn zum Mund führen, schiebt ihn in den Mund und nimmt die Nahrung mit dem Mund auf, ohne dass etwas daneben geht. Es zeigt dieses Verhalten mind. 3x.',
                'order'        => 10,
                'emphasis'     => 1,
                'emphasis_daz' => 1,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 10,
                'abbreviation' => 'FM.18',
                'title'        => 'Mit Stift kritzeln',
                'text'         => 'Kind hält einen Stift stabil und zeichnet/malt damit Striche oder Punkte.',
                'order'        => 24,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 10,
                'abbreviation' => 'FM.19',
                'title'        => 'Gezielt Linien und Formen zeichnen',
                'text'         => 'Kind hält einen Stift in richtiger Haltung (nicht in der Faust) und zeichnet damit gezielt mind. 3 unterschiedliche Linien oder Formen (z.B. senkrechte oder waagerechte mind. 2.5 cm lange Linien, Kringel, Kreise).',
                'order'        => 25,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 11,
                'abbreviation' => 'FM.17',
                'title'        => 'Getränk ohne fremde Hilfe einschenken',
                'text'         => 'Kind füllt selbstständig Flüssigkeit aus einer Flasche oder einer Kanne in ein Glas, ohne dass etwas daneben geht.',
                'order'        => 23,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 12,
                'abbreviation' => 'FM.20',
                'title'        => 'Mit Stift im Dreipunktgriff zeichnen',
                'text'         => 'Kind hält Stift im Dreipunktgriff (zwischen Daumen-, Zeige- und Mittelfinger) und zeichnet damit.',
                'order'        => 26,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 13,
                'abbreviation' => 'FM.24',
                'title'        => 'Kleidungsstücke selbst ausziehen',
                'text'         => 'Kind zieht Hemd, T-Shirt, Pulli, Jacke oder Hose alleine aus, wenn dafür keine Verschlüsse geöffnet werden müssen. Die Mütze vom Kopf ziehen oder eine Socke oder einen Hand-schuh ausziehen, genügt nicht.',
                'order'        => 27,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 13,
                'abbreviation' => 'FM.25',
                'title'        => 'Kleidungsstücke selbst anziehen',
                'text'         => 'Kind zieht Hemd, T-Shirt, Pulli, Jacke oder Hose alleine an. Dabei dürfen vorne und hinten oder rechts und links ver-tauscht sein, aber alle Körperteile müssen in passenden Öff-nungen stecken. Knöpfe und Reißverschlüsse müssen nicht zu sein.',
                'order'        => 28,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 13,
                'abbreviation' => 'FM.26',
                'title'        => 'Reißverschluss der eigenen Jacke auf/ zu ziehen',
                'text'         => 'Kind zieht Reißverschlüsse an Jacken alleine auf- und zu (eine Richtung genügt nicht), wenn es dafür beide Hände braucht: eine zum Ziehen am Zipper und eine zum Gegenziehen am Stoff. (Beim Einfädeln darf geholfen werden. Reißverschlüsse sollen grob sein).',
                'order'        => 29,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 13,
                'abbreviation' => 'FM.31',
                'title'        => 'Langärmeliges Oberteil ohne Hilfe an- oder ausziehen',
                'text'         => 'Kind zieht ein langärmeliges Oberteil selbständig über Kopf an oder aus.',
                'order'        => 30,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 14,
                'abbreviation' => 'FM.35',
                'title'        => 'Runde Formen ausschneiden',
                'text'         => 'Kind schneidet selbstständig eine vorgezeichnete runde Form mit der Schere aus und weicht kaum von der Linie ab.',
                'order'        => 31,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 14,
                'abbreviation' => 'FM.36',
                'title'        => 'Komplexe eckige Formen ausschneiden',
                'text'         => 'Kind schneidet selbstständig eine komplexe Form (z.B. Tannenbaum, Stern) mit Schere so aus, dass die Form eindeutig erkennbar ist.',
                'order'        => 32,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 14,
                'abbreviation' => 'FM.38',
                'title'        => 'Eine Kugel formen',
                'text'         => 'Kind formt (z.B. aus Knete, Teig oder Ton) mit beiden Händen eine Kugel.',
                'order'        => 33,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 15,
                'abbreviation' => 'FM.43',
                'title'        => 'Einfachen Knoten machen',
                'text'         => 'Kind macht alleine einen einfachen Knoten (z.B. beim Ge-schenk packen, Schuhe binden).',
                'order'        => 34,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 16,
                'abbreviation' => 'FM.48',
                'title'        => 'Schraubverschluss öffnen und schließen',
                'text'         => 'Kind öffnet und schließt selbständig ein Gefäß mit schmalem Durchmesser und Schraubdeckel.',
                'order'        => 35,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 17,
                'abbreviation' => 'FM.49',
                'title'        => 'Puzzleteile zusammenfügen',
                'text'         => 'Kind verbindet ohne fremde Hilfe mind. 3 große Puzzle-Teile nahtlos miteinander.',
                'order'        => 36,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 18,
                'abbreviation' => 'KG.03',
                'title'        => 'Aufmerksam betrachten',
                'text'         => 'Kind betrachtet konzentriert ca. 1 Minute oder länger einen unbewegten Gegenstand (z.B. ein Bild, eine Pflanze).',
                'order'        => 11,
                'emphasis'     => 3,
                'emphasis_daz' => 3,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 18,
                'abbreviation' => 'KG.04',
                'title'        => 'Gezielte visuelle Suche',
                'text'         => 'Kind sucht ca. 1 Minute oder länger ganz gezielt bestimmte Objekte unter vielen anderen (z.B. auf Wimmelbildern, oder in einer Spielkiste).',
                'order'        => 12,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 19,
                'abbreviation' => 'KG.08',
                'title'        => 'Aufmerksamkeitsdauer beim Zuhören',
                'text'         => 'Kind lauscht mind. 3 Minuten ruhig und aufmerksam einem Musikstück, einer Geschichte oder einem Gespräch (in einer Sprache, die dem Kind vertraut ist).',
                'order'        => 13,
                'emphasis'     => 4,
                'emphasis_daz' => 4,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 19,
                'abbreviation' => 'KG.09',
                'title'        => 'Gezieltes Hören',
                'text'         => 'Kind hört gezielt aus einem Lied oder aus einem Gespräch ein bestimmtes Wort heraus. Das Wort sollte kein Personen-Name sein.',
                'order'        => 14,
                'emphasis'     => 1,
                'emphasis_daz' => 1,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 20,
                'abbreviation' => 'KG.11',
                'title'        => 'Konzentration bei selbstständiger Aktivität',
                'text'         => 'Kind beschäftigt sich selbstständig mind. 10 Minuten mit dem gleichen Material und verfolgt dabei ein Ziel, ohne sich ablenken zu lassen (Handy-, Tablet-, oder Computerspiele ausgeschlossen).',
                'order'        => 15,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 21,
                'abbreviation' => 'KG.14',
                'title'        => 'Gezielter Wechsel beim Kategorisieren',
                'text'         => 'Kind sortiert Objekte gleicher Art (z.B. Legosteine, Perlen, Bauklötze) auf Bitte hin erst nach Form und anschließend nach der Farbe, ohne sich zu vertun.',
                'order'        => 37,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 22,
                'abbreviation' => 'KG.19',
                'title'        => 'Memory spielen',
                'text'         => 'Kind findet bei Memory-Spielen (28 Teile) zielsicher 2 gleiche Teile unter mind. 10 verbleibenden, wenn diese vorher bereits einmal oder mehrmals aufgedeckt wurden.',
                'order'        => 38,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 23,
                'abbreviation' => 'KG.23',
                'title'        => 'Akustisches Kurzzeitgedächtnis II',
                'text'         => 'Das Kind kann ein vier-silbiges Fantasiewörter (z.B. ri-so-la-mi), oder eine zufällige Zahlenreihe (z.B. 9-3-7-1) nach einmaligem Hören richtig nachsprechen.',
                'order'        => 39,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 23,
                'abbreviation' => 'KG.25',
                'title'        => 'Akustisches Langzeitgedächtnis II',
                'text'         => 'Kind gibt Teile von bekannten Liedern, Reimen, Sprüchen oder Sprachspielen von sich aus (ohne Erinnerungshilfe) wie-der.',
                'order'        => 40,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 24,
                'abbreviation' => 'D.06',
                'title'        => 'Gezielte Verkettung von Teilhandlungen',
                'text'         => 'Kind führt geplant 2 unabhängige Teilhandlungen nachein-ander aus, um ein Ziel zu erreichen (z.B. Becher holen und Getränk einschenken, um zu trinken). Wichtig ist das Erkennen eines Handlungsplans aus mindestens 2 abgrenzbaren Teil-schritten.',
                'order'        => 43,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 24,
                'abbreviation' => 'D.07',
                'title'        => 'Verwendung von Gegenständen als Hilfsmitteln',
                'text'         => 'Kind hat kein geeignetes Werkzeug, um ein bestimmtes Ziel zu erreichen (z.B. keine Schaufel, um Sand zu graben) und verwendet dann spontan (ohne Hinweis von anderen) ein Hilfsmittel, das sonst nicht in dieser Funktion verwendet wird (z.B. Löffel).',
                'order'        => 44,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 24,
                'abbreviation' => 'D.08',
                'title'        => 'Verschiedene Lösungswege ausprobieren',
                'text'         => '´Kind steht vor einem Problem, für das es die Lösung nicht gleich findet. Auch wenn es zunächst scheitert, denkt es er-kennbar über die Lösung nach und probiert mind. 2 Möglichkeiten aus, um sein Ziel doch noch zu erreichen (Frage nach Lösungsweg zählt nicht).',
                'order'        => 45,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 25,
                'abbreviation' => 'D.03',
                'title'        => 'Als-ob-Spiele',
                'text'         => 'Kind weist Gegenständen (nicht Personen!) im Spiel eine Bedeutung zu, die nicht zu ihrem Aussehen und/oder zu ihrer normalen Funktion passen (Zweckentfremdung). Es spielt Als-ob-Spiele (z.B. Besen als Pferd, Kiste als Boot).',
                'order'        => 41,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 26,
                'abbreviation' => 'D.05',
                'title'        => 'Beginnendes Sortierverhalten',
                'text'         => 'Kind legt Gegenstände verschiedener Art (z.B. Murmeln und Bauklötze) in getrennte Behälter. Die Behälter sind bereits mit Objekten der jeweiligen Kategorie befüllt. Es werden mind. 2 neue Objekte jeder Art vom Kind richtig einsortiert.',
                'order'        => 42,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 27,
                'abbreviation' => 'KF.09',
                'title'        => 'Fantasie-Figuren oder -Objekte erfinden',
                'text'         => 'Kind erfindet eine eigene Fantasie-Figur / ein Fantasie-Objekt und stellt sie/ es genauer dar (verbal oder auf andere Weise).',
                'order'        => 48,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 27,
                'abbreviation' => 'KF.11',
                'title'        => 'Sinnvolle Begründungen geben',
                'text'         => 'Das Kind formuliert eigene, in sich plausible Erklärungen für eine Beobachtung.',
                'order'        => 49,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 28,
                'abbreviation' => 'KF.01',
                'title'        => 'Planvoll und strukturiert handeln',
                'text'         => 'Kind führt spontan mind. 3 Handlungsschritte durch, die alle zusammenhängen und auf ein übergeordnetes Ziel hinführen (z.B. erst Einzelteile basteln, dann alles zusammenfügen).',
                'order'        => 46,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 29,
                'abbreviation' => 'KF.04',
                'title'        => 'Gezielt Experimentieren',
                'text'         => 'Beim Experimentieren verändert das Kind von sich aus ganz bewusst einzelne Aspekte einer Situation, um herauszufin-den, welche Auswirkungen das hat (z.B. was passiert, wenn man etwas dazu tut, wegnimmt, verschiebt, erwärmt).',
                'order'        => 47,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 30,
                'abbreviation' => 'SV.03',
                'title'        => 'Ein geschriebenes Wort erkennen',
                'text'         => 'Kind erkennt seinen eigenen Namen oder ein anderes Wort mit mind. 3 Buchstaben am Schriftbild wieder.',
                'order'        => 50,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 31,
                'abbreviation' => 'SV.17',
                'title'        => 'Menge von drei Elementen einzeln abzählen',
                'text'         => 'Kind zählt eine Menge von 3 Gegenständen ab (z.B. drei ei-gene Finger oder 3 Bonbons). Es zeigt auf jedes Objekt einmal und nennt dabei die passende Zahl.',
                'order'        => 51,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 32,
                'abbreviation' => 'SV.20',
                'title'        => 'Gefäße ineinander stapeln',
                'text'         => 'Kind stapelt mind. 3 unterschiedlich große Gefäße ineinan-der (z.B. Plastiktöpfchen, Becher).',
                'order'        => 52,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 33,
                'abbreviation' => 'S1.08',
                'title'        => 'Mindestens 50 unterschiedliche Wörter aktiv verwenden',
                'text'         => 'Kind hat einen aktiven Wortschatz von mind. 50 verschiedenen Wörtern. Die gleiche Lautfolge wird in verschiedenen Situationen zur Beschreibung des gleichen Sachverhaltes verwendet. Machen Sie vor der Bewertung eine Liste der gesprochenen Worte (ein passendes Formular finden Sie auf Seite X im BeoTool (kulturspezifisch abfragen "arabisch für Hund).',
                'order'        => 16,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 34,
                'abbreviation' => 'S2.01',
                'title'        => 'Verwendung von Finalwörtern',
                'text'         => 'Kind benutzt Worte wie „auf“, „zu“, „ab“, „aus“ oder „weg“, die das Ende eines Vorgangs beschreiben. Das gleiche Wort wird in verschiedenen Situationen wiederholt passend verwendet.',
                'order'        => 53,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 34,
                'abbreviation' => 'S2.02',
                'title'        => 'Verwendung von Mehrzahlwörtern',
                'text'         => 'Kind benennt Objekte in Mehrzahl und verändert dafür das Wortende (z.B. „Autos“ statt „Auto“). Wenn es dabei zu lusti-gen Formbildungen (z.B. „Ananässe“, „Mädchens“) kommt, gilt das auch.',
                'order'        => 54,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 34,
                'abbreviation' => 'S2.03',
                'title'        => 'Verwendung von Farbwörtern',
                'text'         => 'Kind benennt die Farbe eines Gegenstandes in verschiedenen Situationen richtig.',
                'order'        => 55,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 34,
                'abbreviation' => 'S2.04',
                'title'        => 'Verwendung der Wörter „ich“ und „du“',
                'text'         => 'Kind spricht von sich selbst als „ich“ und benennt sein Gegenüber als „du“. Dieses Verhalten wird in unterschiedlichen Situationen gezeigt.',
                'order'        => 56,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 35,
                'abbreviation' => 'S2.05',
                'title'        => 'Einfache Sätze verstehen',
                'text'         => 'Kind zeigt durch sein Verhalten, dass es einen Satz versteht, obwohl sich die Bedeutung nicht aus der Situation erschließen lässt und keine Gesten (z.B. Zeigen) zur Verständigung eingesetzt werden.',
                'order'        => 57,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 35,
                'abbreviation' => 'S2.06',
                'title'        => 'Zweiwortsätze bilden',
                'text'         => 'Kind bezieht 2 verschiedene Wörter sinnvoll aufeinander (z.B. „Puppe weg“, „Mama laufen“, „Lilo groß“, „Papa Auto“), sodass sie eine Bedeutungseinheit bilden.',
                'order'        => 58,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 35,
                'abbreviation' => 'S2.07',
                'title'        => 'Drei- und Mehrwortsätze bilden',
                'text'         => 'Kind bildet einfache Sätze, die aus 3 oder mehr Wörtern bestehen (z.B. „Papa Auto fahren“, „Mama, Bonbon geben“).',
                'order'        => 59,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 36,
                'abbreviation' => 'S3.01',
                'title'        => 'Konkrete Bezeichnungen für Objekte verwenden',
                'text'         => 'Kind benennt Personen, Tiere, Gegenstände etc.',
                'order'        => 60,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 36,
                'abbreviation' => 'S3.02',
                'title'        => 'Bezeichnungen für abstrakte Dinge verwenden',
                'text'         => 'Kind benennt Dinge, die man nicht anfassen kann (z.B. Woche, Lied, Gefühl).',
                'order'        => 61,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 36,
                'abbreviation' => 'S3.04',
                'title'        => 'Konkrete Tätigkeitsbeschreibungen verwenden',
                'text'         => 'Kind nutzt Wörter, die konkrete und direkt beobachtbare Handlungen beschreiben (z.B. malen, laufen, essen).',
                'order'        => 62,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 36,
                'abbreviation' => 'S3.06',
                'title'        => 'Zeitbegriffe benennen und unterscheiden',
                'text'         => 'Kind zeigt Verständnis für Zeitbegriffe (gestern, heute, morgen, oder morgens, mittags, abends). Es verwendet mehrere dieser Worte in passenden Zusammenhängen.',
                'order'        => 63,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 36,
                'abbreviation' => 'S3.07',
                'title'        => 'Raumbeziehungen benennen und unterscheiden',
                'text'         => 'Kind zeigt Verständnis für Lagebezeichnungen (vor, hinter, unter, über, zwischen, neben). Es verwendet mehrere dieser Worte in passenden Zusammenhängen.',
                'order'        => 64,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 36,
                'abbreviation' => 'S3.08',
                'title'        => 'Mentale Aktivitäten benennen und unterscheiden',
                'text'         => 'Kind verwendet Wörter, die sich auf nicht direkt sichtbare Prozesse beziehen, wie denken, wissen, meinen, glauben, fühlen.',
                'order'        => 65,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 37,
                'abbreviation' => 'S3.12',
                'title'        => 'Mehrzahlbildung',
                'text'         => 'Kind bildet die Mehrzahlform richtig (z.B. Bäum-e, Gräse-r, Blume-n, Auto-s).',
                'order'        => 66,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 38,
                'abbreviation' => 'S3.19',
                'title'        => 'Nebensätze bilden',
                'text'         => 'Kind bildet Sätze, die aus mind. 2 Satzteilen bestehen (z.B. „Ich frage mich, was Du in der Tasche hast?“ „Gib mir den Teddy, den ich so mag!“).',
                'order'        => 67,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 38,
                'abbreviation' => 'S3.23',
                'title'        => 'Flexibler Satzbau',
                'text'         => 'Kind verwendet unterschiedliche Satzanfänge. Es beginnt z.B. mit einer Zeit- oder Ortsangabe („Abends gehe ich ins Bett“; „Zuhause lese ich immer“).',
                'order'        => 68,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 39,
                'abbreviation' => 'S3.30',
                'title'        => 'Entscheidungsfragen stellen',
                'text'         => 'Kind stellt ein Verb an den Anfang seiner Frage (z.B. „Teilst Du mit mir?“ „Kannst Du das schon?“).',
                'order'        => 69,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 39,
                'abbreviation' => 'S3.31',
                'title'        => 'W-Fragen verstehen',
                'text'         => 'Kind versteht die Bedeutung unterschiedlicher W-Worte (z.B. wer, warum, wie, wann, wo).',
                'order'        => 70,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 39,
                'abbreviation' => 'S3.32',
                'title'        => 'W-Frage stellen',
                'text'         => 'Kind nutzt mind. 3 unterschiedliche Fragewörter wie "wer, wie, was, wo, wieso, weshalb, warum, wohin, wozu", um mehr Informationen über einen Sachverhalt zu erhalten.',
                'order'        => 71,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 39,
                'abbreviation' => 'S3.33',
                'title'        => 'Fragen ausführlich beantworten',
                'text'         => 'Das Kind antwortet auf differenzierte Fragen ausführlich, genau und in richtig formulierten Sätzen. Die Antwort besteht aus mind. 3 sinnvoll aufeinander bezogenen Sätzen.',
                'order'        => 72,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 40,
                'abbreviation' => 'S3.34',
                'title'        => 'In verständlicher Weise über Erfahrungen berichten',
                'text'         => 'Kind berichtet von einer Erfahrung oder einem Erlebnis so, dass man verstehen kann, was passiert ist (z.B. von einem Ausflug, einem Fest, vom Alltag).',
                'order'        => 73,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 40,
                'abbreviation' => 'S3.36',
                'title'        => 'Geschichten sprachlich komplex wiedergeben',
                'text'         => 'Beim Geschichten nacherzählen nutzt das Kind Fürwörter (er, sie, es) und Bindewörter (z.B. und, weil, aber). Außerdem macht es konkrete Zeitangaben (danach, jetzt, plötzlich).',
                'order'        => 74,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 40,
                'abbreviation' => 'S3.37',
                'title'        => 'Kurze Aufträge verstehen',
                'text'         => 'Das Kind versteht Aufträge, die aus 1-2 verschiedenen Tätigkeiten bestehen (z.B. „Zieh‘ dir die Jacke aus und komm dann zu mir.“).',
                'order'        => 75,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 41,
                'abbreviation' => 'SB.14',
                'title'        => 'Emotionale Rückversicherung',
                'text'         => 'Wenn das Kind unsicher ist, was es von einer neuen Situation, einem unvertrauten Gegenstand oder einer unbekannten Person halten soll, schaut es zur Bezugsperson, um in ihrem Gesicht ablesen zu können, wie sie zu der Sache steht.',
                'order'        => 76,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 42,
                'abbreviation' => 'SB.15',
                'title'        => 'Teilen',
                'text'         => 'Kind teilt Nahrung, Getränke oder Spielmaterial freiwillig mit einem anderen Menschen, wenn es sieht, dass die andere Person etwas davon haben möchte.',
                'order'        => 77,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 42,
                'abbreviation' => 'SB.17',
                'title'        => 'Freiwilliges Helfen',
                'text'         => 'Kind zeigt spontan Bemühen, andere zu unterstützen. Es hilft Erwachsenen (z.B. bei der Hausarbeit) oder anderen Kindern im Spiel bei der Umsetzung eines Vorhabens, ohne dazu auf-gefordert worden zu sein.',
                'order'        => 78,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 43,
                'abbreviation' => 'SB.18',
                'title'        => 'Assoziatives Spiel',
                'text'         => 'Kind beobachtet beim eigenen Spiel, was ein anderes Kind gerade tut. Es greift nicht in das Spiel des anderen ein, nimmt aber Anregungen auf (z.B. Imitation von Handlungen anderer Kinder im Sandkasten, Kommentieren des Spiels eines anderen Kindes).',
                'order'        => 79,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 43,
                'abbreviation' => 'SB.19',
                'title'        => 'Bewegungsspiel',
                'text'         => 'Kind spielt ein Spiel, für das es andere Kinder braucht und sich bewegen muss (z.B. Fangen, Ballspiele, Verstecken). Das Spiel dauert länger als 3 Minuten.',
                'order'        => 80,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 43,
                'abbreviation' => 'SB.20',
                'title'        => 'Konstruktionsspiel',
                'text'         => 'Kind baut mehr als 3 Minuten lang etwas auf (z.B. Sandburg, Höhle). Das Bauziel, die Aufgabenteilungen oder der Spielverlauf werden mit den Spielpartnern (älteren Kindern oder Erwachsenen) gemeinsam besprochen.',
                'order'        => 81,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 43,
                'abbreviation' => 'SB.21',
                'title'        => 'Rollenspiel',
                'text'         => 'Kind versetzt sich in eine Rolle (z.B. Verkäufer, Doktor, Kapitän) und spielt länger als 3 Minuten, diese Person zu sein. Es können Verkleidungen oder Spielfiguren zum Einsatz kommen.',
                'order'        => 82,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 44,
                'abbreviation' => 'SE.07',
                'title'        => 'Gefühle darstellen',
                'text'         => 'Kind gibt vor, bestimmte Gefühle zu haben (z.B. Schmerz, Traurigkeit, Furcht, Freude), etwa im Rollenspiel.',
                'order'        => 83,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 44,
                'abbreviation' => 'SE.08',
                'title'        => 'Flunkern',
                'text'         => 'Kind versucht, einen anderen Menschen von etwas zu überzeugen, das nicht der Wahrheit entspricht.',
                'order'        => 84,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 44,
                'abbreviation' => 'SE.09',
                'title'        => 'Perspektivenübernahme',
                'text'         => 'Kind versteht, dass jeder Mensch anders über die gleiche Sache denken kann. Auch wenn die Perspektive eines anderen von seiner eigenen abweicht, kann es sie erfassen.',
                'order'        => 85,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 45,
                'abbreviation' => 'SE.13',
                'title'        => 'Wünsche und Vorlieben anderer berücksichtigen',
                'text'         => 'Das Kind berücksichtigt die Wünsche und Vorlieben anderer Kinder (z.B. bei der Auswahl von Spielen oder Spielmaterial) im eigenen Handeln oder es fragt nach den Wünschen und Vorlieben seines Spielpartners.',
                'order'        => 86,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 46,
                'abbreviation' => 'SE.19',
                'title'        => 'Spontanes Teilen von Ressourcen',
                'text'         => 'Kind teilt öfters von sich aus etwas, für das sich außer ihm noch ein anderes Kind interessiert (z.B. Zeit auf der Schaukel, Spiel-Material, Kekse).',
                'order'        => 87,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 47,
                'abbreviation' => 'SE.23',
                'title'        => 'Gemeinsames Konstruktionsspiel mit Plan',
                'text'         => 'Kind baut mit einem anderen Kind gemeinsam ein Spielszenario auf und spricht seine Pläne dabei ab.',
                'order'        => 88,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 48,
                'abbreviation' => 'SE.30',
                'title'        => 'Um Erlaubnis fragen',
                'text'         => 'Wenn das Kind sich nicht sicher ist, ob eine Handlung erlaubt ist, fragt es erst bei Erwachsenen nach (verbal oder nonverbal).',
                'order'        => 89,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 48,
                'abbreviation' => 'SE.32',
                'title'        => 'Ungerechtigkeiten benennen',
                'text'         => 'Kind teilt es einem Erwachsenen mit, wenn es dessen Entscheidung oder Handlung ungerecht findet.',
                'order'        => 90,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 48,
                'abbreviation' => 'SE.33',
                'title'        => 'Regeln und Verbote hinterfragen',
                'text'         => 'Das Kind hinterfragt den Sinn und Zweck von Verboten und Regeln Erwachsenen gegenüber.',
                'order'        => 91,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 49,
                'abbreviation' => 'SE.37',
                'title'        => 'Gemeinschaftsaufgaben freiwillig arbeitsteilig erledigen',
                'text'         => 'Kind beteiligt sich bereitwillig an der Erledigung von Pflichten gegenüber der Gemeinschaft (z.B. Tisch decken, Aufräumen).',
                'order'        => 92,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 50,
                'abbreviation' => 'SR.04',
                'title'        => 'Impulse eigenständig kontrollieren',
                'text'         => 'Kind hemmt ein eigenes Bedürfnis oder Gefühl von sich aus (z.B. nicht sofort schreien, wenn es sich wehgetan hat; nicht hauen, wenn es sich geärgert hat; nicht essen, solange noch nicht alle am Tisch sitzen).',
                'order'        => 93,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 51,
                'abbreviation' => 'SR.07',
                'title'        => 'Auf das Töpfchen oder die Toilette gehen wollen',
                'text'         => 'Kind macht deutlich, dass es auf Toilette oder auf das Töpfchen muss, bevor die Hose voll ist oder es folgt bereitwillig einem Erwachsenen, der einen Gang zur Toilette / zum Töpfchen anbietet.',
                'order'        => 94,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 52,
                'abbreviation' => 'SR.12',
                'title'        => 'Zielorientierung halten',
                'text'         => 'Wenn das Kind etwas schaffen möchte, zeigt es Vertrauen in seine eigenen Fähigkeiten, indem es trotz mehrerer Fehlversuche länger versucht, doch noch ans Ziel zu kommen.',
                'order'        => 95,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 53,
                'abbreviation' => 'SR.15',
                'title'        => 'Warten, bis man an der Reihe ist',
                'text'         => 'Kind wartet bereitwillig, bis es dran ist und drängelt sich nicht vor.',
                'order'        => 96,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 54,
                'abbreviation' => 'SR.19',
                'title'        => 'Selbstregulation im Umgang mit Ärger und Wut',
                'text'         => 'Wenn Kind Ärger oder Wut fühlt, gelingt es ihm, sich selbst zu beruhigen oder es drückt seine Gefühle aus, ohne andere körperlich oder mit Worten anzugreifen.',
                'order'        => 97,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 55,
                'abbreviation' => 'G.10',
                'title'        => 'Stolz',
                'text'         => 'Kind zeigt deutliche Freude, Bewusstheit und Selbstbewusstsein über eigene Leistungen (z.B. über etwas, das es gemacht hat). Andere sollen sehen/hören, was das Kind kann/produziert hat.',
                'order'        => 98,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 55,
                'abbreviation' => 'G.13',
                'title'        => 'Trotz',
                'text'         => 'Kind erkennt, dass die Bezugsperson es dazu bringen will, etwas Bestimmtes zu tun oder zu lassen. Es reagiert mit heftigem Widerstand und beharrt auf der Durchsetzung seiner eigenen Ziele.',
                'order'        => 99,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 55,
                'abbreviation' => 'G.14',
                'title'        => 'Mitgefühl',
                'text'         => 'Kind zeigt durch sein Verhalten, dass es die Gefühle anderer versteht und ihnen helfen möchte. Es reagiert empathisch auf einen Menschen (z.B. indem es ein anderes Kind tröstet oder verteidigt).',
                'order'        => 100,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 56,
                'abbreviation' => 'G.16',
                'title'        => 'Über eigene Körperzustände reden',
                'text'         => 'Kind teilt anderen Menschen sprachlich etwas über seine eigenen Körperzustände mit (z.B. Müdigkeit, Hunger, Schmerzen, Temperaturempfindungen).',
                'order'        => 101,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 56,
                'abbreviation' => 'G.17',
                'title'        => 'Über eigene Gefühle und Gefühlsäußerungen reden',
                'text'         => 'Kind teilt anderen Menschen sprachlich etwas über seine eigenen Gefühle mit. Es benutzt Be-/Umschreibungen, die sich auf eigene Gefühlsäußerungen beziehen (z.B. weinen, lachen) oder direkt auf die Gefühle selbst (z.B. böse / traurig sein).',
                'order'        => 102,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 56,
                'abbreviation' => 'G.18',
                'title'        => 'Über Körperzustände, Gefühle und Gefühlsäußerungen anderer reden',
                'text'         => 'Kind spricht über die Körperzustände oder Gefühle eines anderen Menschen. Es verwendet Wörter, die entsprechende Zustände oder Gefühle beschreiben und ordnet sie anderen Personen zu (z.B. „Kind hat Aua/ ist böse“).',
                'order'        => 103,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '2.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 57,
                'abbreviation' => 'G.19',
                'title'        => 'Erkennen und benennen, warum ein anderes Kind weint',
                'text'         => 'Kind erkennt und benennt den Grund für das Weinen eines anderen Kindes (z.B. vor Schmerzen, Ärger, Traurigkeit).',
                'order'        => 104,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 58,
                'abbreviation' => 'G.25',
                'title'        => 'Grundgefühle im eigenen Erleben unterscheiden',
                'text'         => 'Kind gibt auf Nachfrage an, ob es sich freut, traurig, ärgerlich bzw. wütend oder ängstlich ist. Es unterscheidet beim Sprechen zwischen diesen Emotionen.',
                'order'        => 105,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
            array_merge($commonOptions, [
                'subdomain_id' => 59,
                'abbreviation' => 'G.27',
                'title'        => 'Gründe für eigene Empfindungen benennen',
                'text'         => 'Kind erklärt, was bei ihm ein bestimmtes Gefühl ausgelöst hat (z.B. „Der hat mich nicht in Ruhe gelassen und da bin ich wütend geworden“).',
                'order'        => 106,
                'emphasis'     => 2,
                'emphasis_daz' => 2,
                'age'          => '4.5',
            ]),
        ]);
    }
};
